// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACE_YOUR_ANDROID_API_KEY_HERE',
    appId: '1:1073460631405:android:f4810d5a1323653c4fac64',
    messagingSenderId: '1073460631405',
    projectId: 'erestro',
    storageBucket: 'erestro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACE_YOUR_IOS_API_KEY_HERE',
    appId: '1:1073460631405:ios:bf7297daed26ac584fac64',
    messagingSenderId: '1073460631405',
    projectId: 'erestro',
    storageBucket: 'erestro.appspot.com',
    androidClientId:
        '1073460631405-11ghloretur6nep53elj5cp36qo7n3bo.apps.googleusercontent.com',
    iosClientId:
        '1073460631405-gd91ub0abuh09f12o1sdvisdhc0ivvln.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.erestrorider',
  );
}
